version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  python-service:
    build: ./python-service
    ports:
      - "5000:5000"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airport
      POSTGRES_PASSWORD: mag123
      POSTGRES_DB: mag_airport
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: