version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - kafka
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=localhost:9092

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airport
      POSTGRES_PASSWORD: mag123
      POSTGRES_DB: mag_airport
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  python-service:
    build: ./python-service
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  pgdata:
